- id: compile-messages
  name: run compilemessages django admin command
  description: prevent outdated translations to be committed
  language: python
  entry: compile-messages
  files: '.*\.po'
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
